In [16]:
import numpy as np

# Wrong sign, equation (9)
class LinearSearcher:
    def __init__(self, func, grad):
        self.alpha = 1.0
        self.sigma = 0.05
        self.func = func
        self.grad = grad
    
    def search(self, w):
        self.alpha *= 2
        gradient_value = self.grad(w)
        func_value = self.func(w)
        while self.func(w - self.alpha * gradient_value) - func_value > \
              -self.alpha * self.sigma * np.linalg.norm(gradient_value, 2):
            self.alpha /= 2
        return self.alpha


# Remind about typo in a task: sign should be inverted (equation 8)
def stop_criterion(grad, w, w0, eps):
    # eps should be relative 
    return np.linalg.norm(grad(w), 2) ** 2 < eps * np.linalg.norm(grad(w0), 2) ** 2


def gradient_descent(func, grad, w0):
    searcher = LinearSearcher(func, grad)
    w = w0.copy()
    while not stop_criterion(grad, w, w0, 1e-20):
        alpha = searcher.search(w)
        gradient_value = grad(w)
        delta_w = alpha * gradient_value
        w -= delta_w
    return w


def test_function(xs):
    return (xs[0][0] - 2) ** 2 + (xs[0][1] - 1) ** 2


def test_function_gradient(xs):
    return np.array([[2 * (xs[0][0] - 2), 
                     2 * (xs[0][1] - 1)]])


w0 = np.array([[100, 500]], dtype=np.float64)
gradient_descent(test_function, test_function_gradient, w0)

array([[2., 1.]])

$Q(X, y, w) = \sum_{i = 1}^m ln(1 + e^{-y_i (x_i, w)}) + \frac{\lambda}{2}\|w\|^2 = [1 \space 1 \ldots 1] \cdot ln(1 + e^{-(y, Xw^T)}) + \frac{\lambda}{2}\|w\|^2$

$\frac{d Q(X, y, w)}{\delta w_k} = \sum_{i=1}^{m}(ln(1 + e^{-y_i (x_i, w)}))_{w_k}^{'} + \lambda w_k = \sum_{i = 1}^{m}\frac{-y_ix_ke^{-y_i(x_i,w)}}{1 + e^{-y_i(x_i,w)}} + \lambda w_k$

$\nabla Q(X, y, w) = (X^T\frac{-(y, e^{-(y, X w^T)})}{1 + e^{-(y, X w^T)}})^T + \lambda w$

$\frac{d Q(X, y, w)}{\delta w_k \delta w_j} = (\sum_{i = 1}^{m}\frac{-y_ix_ke^{-y_i(x_i,w)}}{1 + e^{-y_i(x_i,w)}} + \lambda w_k)_{w_j}^{'} = \sum_{i=1}^{m}\frac{y_i^2x_ke^{-y_i(x_i, w)}x_{ij}}{(1 + e^{-y_i(x_i,w)})^2} + \lambda [k == j]$

$H(X, y, w) = ([1 \space 1 \ldots 1]_m \cdot X) \cdot (X^T\frac{(y^2, e^{-(y, X w^T)})}{(1 + e^{-(y, X w^T)})^2})) + \lambda E$

In [19]:
X = np.array([[1, 2], [1, 4], [3, 2]])
y = np.array([[1], [1], [0]])
w = np.array([[1, 2]])
reg = 1
X, y, w

(array([[1, 2],
        [1, 4],
        [3, 2]]),
 array([[1],
        [1],
        [0]]),
 array([[1, 2]]))

In [51]:
def logistic_regression_function(X, y, w, reg):
    samples = X.shape[0]
    return np.ones((1, samples)).dot(np.log(1 + np.exp(-y * X.dot(w.T)))).item() + reg * w[0] * w[0]

def logistic_regression_gradient(X, y, w, reg):
    exp_part = np.exp(-y * X.dot(w.T))
    return X.T.dot(-y * exp_part / (1 + exp_part)).T + reg * w

def logistic_regression_hessian(X, y, w, reg):
    m, n = X.shape
    exp_part = np.exp(-y * X.dot(w.T))
    return np.ones((1, m)).dot(X).dot(X.T.dot(y * y * exp_part / (1 + exp_part) ** 2)) + reg * np.eye(n)

In [52]:
logistic_regression_function(X, y, w, reg)

array([1.69998593, 4.69998593])